FROM node:20.18.3-alpine3.21 as build
WORKDIR /opt/backend
COPY package.json .
COPY *.js .
RUN npm install



FROM node:20.18.3-alpine3.21
RUN addgroup -S expense && adduser -S expense -G expense && \
    mkdir /opt/backend && \
    chown -R expense:expense /opt/backend
ENV DB_HOST="mysql"
WORKDIR /opt/backend
COPY --from=build /opt/backend /opt/backend
USER expense
CMD ["node","index.js"]

