apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: expense
  region: us-east-1

managedNodeGroups:
  - name: expense
    instanceTypes: ["m2.medium", "m3.medium"]
    desiredCapacity: 3
    spot: true
